name = "my-worker"
type = "javascript"

# Define the worker script file
[build]
command = "npm install"

[env.production]
workers_dev = false
compatibility_date = "2024-08-19"

# Define routes for the worker
[[routings]]
pattern = "*"
script = "index"