export const PTR_DATA = [
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "枫叶千支",
    Class: "Rogue",
    Mode: "SC",
    "Build Name": "Dash Pull Barrage",
    "Skills Used":
      "Barrage, Dark_Shroud, Smoke_Grenade, Caltrops, Dash, Shadow_Clone",
    "Run Video": "https://www.bilibili.com/video/BV13bpeeaEhN/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Earthen_Bulwark",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "Zir",
    Class: "Rogue",
    Mode: "SC",
    "Build Name": "Cold Rapid Fire",
    "Skills Used":
      "Puncture, Rapid_Fire, Smoke_Grenade, Caltrops, Dash, Cold_Imbuement",
    "Run Video": "https://www.bilibili.com/video/BV13bpeeaEhN/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "鳳華",
    Class: "Sorcerer",
    Mode: "SC",
    "Build Name": "Forb LS",
    "Skills Used":
      "Frozen_Orb, Flame_Shield, Ice_Armor, Teleport, Lightning_Spear, Unstable_Currents",
    "Run Video": "https://www.bilibili.com/video/BV1U4p8ejE3c/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "秋葉-Akiha-",
    Class: "Necromancer",
    Mode: "SC",
    "Build Name": "Bone Spirit",
    "Skills Used":
      "Blood_Mist, Bone_Prison, Bone_Spirit, Decrepify, Corpse_Tendrils, Bone_Storm",
    "Run Video": "https://www.bilibili.com/video/BV1fnHReYEq1/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "SKULM",
    Class: "Necromancer",
    Mode: "SC",
    "Build Name": "Soul Spirit",
    "Skills Used":
      "Blood_Mist, Bone_Prison, Bone_Spirit, Decrepify, Corpse_Tendrils, Soulrift",
    "Run Video": "https://www.bilibili.com/video/BV1fnHReYEq1/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "Andy",
    Class: "Barbarian",
    Mode: "SC",
    "Build Name": "Throw Barb",
    "Skills Used":
      "Rallying_Cry, War_Cry, Steel_Grasp, Iron_Skin, Wrath_Of_The_Berserker, Mighty_Throw",
    "Run Video": "https://www.youtube.com/watch?v=mIC8uA1dl0Y",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "Mekuna",
    Class: "Sorcerer",
    Mode: "SC",
    "Build Name": "Forb LS",
    "Skills Used":
      "Frozen_Orb, Flame_Shield, Ice_Armor, Teleport, Lightning_Spear, Unstable_Currents",
    "Run Video": "https://www.youtube.com/watch?v=9JA3DAe3Zzs",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "Roxy",
    Class: "Sorcerer",
    Mode: "SC",
    "Build Name": "Azurewrath Chain Lightning",
    "Skills Used":
      "Familiar, Chain_Lightning, Ice_Armor, Teleport, Ice_Blades, Unstable_Currents",
    "Run Video": "https://www.youtube.com/watch?v=s7sOjwO5BYw",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },

  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "da_lin-",
    Class: "Druid",
    Mode: "SC",
    "Build Name": "Lightning Storm",
    "Skills Used":
      "Landslide, Blood_Howl, Cyclone_Armor, Earthen_Bulwark, Wolves, Rabies",
    "Run Video": "https://www.bilibili.com/video/BV1M6pLe3Eez/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "10:08",
    Player: "Blurosity",
    Class: "Necromancer",
    Mode: "SC",
    "Build Name": "Bone Wave",
    "Skills Used":
      "Blood_Mist, Blight, Blood_Lance, Decrepify, Corpse_Tendrils, Blood_Wave",
    "Run Video": "https://www.bilibili.com/video/BV1fnHReYEq1/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
];
