export const PTR_DATA = [
  {
    Date: "10/1/2024",
    Tier: "99",
    "Time Used": "10:50",
    Player: "Natural World",
    Class: "Spiritborn",
    Mode: "SC",
    "Build Name": "Firebolt",
    "Skills Used":
      "Fire_Bolt, Fireball, Flame_Shield, Ice_Armor, Ice_Blades, Firewall",
    "Run Video": "https://www.youtube.com/",
    "Run Comment": "Season 6 Runewords",
    "Build Planner": "https://maxroll.gg",
    Runewords: "War_Cry, Earthen_Bulwark",
  },
  {
    Date: "10/1/2024",
    Tier: "99",
    "Time Used": "10:50",
    Player: "Barb Nation  ",
    Class: "Barbarian",
    Mode: "SC",
    "Build Name": "WW Bleed",
    "Skills Used":
      "Whirlwind, Challenging_Shout, Iron_Skin, Rallying_Cry, War_Cry, Call_Of_The_Ancients",
    "Run Video": "https://www.youtube.com/",
    "Run Comment": "Season 6 Runewords",
    "Build Planner": "https://maxroll.gg",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "99",
    "Time Used": "10:50",
    Player: "Rogue Society",
    Class: "Rogue",
    Mode: "SC",
    "Build Name": "Poison Ivy",
    "Skills Used":
      "Barrage, Poison_Trap, Smoke_Grenade, Shadow_Step, Poison_Imbuement, Shadow_Clone",
    "Run Video": "https://www.youtube.com/",
    "Run Comment": "Season 6 Runewords",
    "Build Planner": "https://maxroll.gg",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "99",
    "Time Used": "10:50",
    Player: "Sorc Kingdom",
    Class: "Sorcerer",
    Mode: "SC",
    "Build Name": "Cold Flash",
    "Skills Used":
      "Frozen_Orb, Flame_Shield, Ice_Armor, Teleport, Lightning_Spear, Unstable_Currents",
    "Run Video": "https://www.youtube.com/",
    "Run Comment": "Season 6 Runewords",
    "Build Planner": "https://maxroll.gg",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "99",
    "Time Used": "10:50",
    Player: "Druid Domain",
    Class: "Druid",
    Mode: "SC",
    "Build Name": "Asura",
    "Skills Used":
      "Landslide, Blood_Howl, Cyclone_Armor, Earthen_Bulwark, Wolves, Petrify",
    "Run Video": "https://www.youtube.com/",
    "Run Comment": "Season 6 Runewords",
    "Build Planner": "https://maxroll.gg",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "99",
    "Time Used": "10:50",
    Player: "Necro Realm",
    Class: "Necromancer",
    Mode: "SC",
    "Build Name": "Bone Shakalaka",
    "Skills Used":
      "Blood_Mist, Bone_Prison, Bone_Spirit, Decrepify, Corpse_Tendrils, Bone_Storm",
    "Run Video": "https://www.youtube.com/",
    "Run Comment": "Season 6 Runewords",
    "Build Planner": "https://maxroll.gg",
    Runewords: "War_Cry, Petrify",
  },
];
