export const PTR_DATA = [
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "3:12",
    Player: "枫叶千支",
    Class: "Rogue",
    Mode: "SC",
    "Build Name": "Firebolt",
    "Skills Used":
      "Barrage, Dark_Shroud, Smoke_Grenade, Caltrops, Dash, Shadow_Clone",
    "Run Video": "https://www.bilibili.com/video/BV13bpeeaEhN/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "https://www.d2core.com/d4/planner?bd=1oku&ptr=1",
    Runewords: "War_Cry, Earthen_Bulwark",
  },

  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "2:01",
    Player: "鳳華",
    Class: "Sorcerer",
    Mode: "SC",
    "Build Name": "Forb LS",
    "Skills Used":
      "Frozen_Orb, Flame_Shield, Ice_Armor, Teleport, Lightning_Spear, Unstable_Currents",
    "Run Video": "https://www.bilibili.com/video/BV1U4p8ejE3c/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "https://www.d2core.com/d4/planner?bd=1ohY&ptr=1",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "4:20",
    Player: "秋葉-Akiha-",
    Class: "Necromancer",
    Mode: "SC",
    "Build Name": "Bone Spirit",
    "Skills Used":
      "Blood_Mist, Bone_Prison, Bone_Spirit, Decrepify, Corpse_Tendrils, Bone_Storm",
    "Run Video": "https://www.bilibili.com/video/BV1fnHReYEq1/",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "4:20",
    Player: "Andy",
    Class: "Barbarian",
    Mode: "SC",
    "Build Name": "Throw Barb",
    "Skills Used":
      "Rallying_Cry, War_Cry, Steel_Grasp, Iron_Skin, Wrath_Of_The_Berserker, Hammer_Of_The_Ancients",
    "Run Video": "https://www.youtube.com/watch?v=mIC8uA1dl0Y",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
  {
    Date: "10/1/2024",
    Tier: "100",
    "Time Used": "2:22",
    Player: "Placeholder",
    Class: "Druid",
    Mode: "SC",
    "Build Name": "Vicious Vortex",
    "Skills Used":
      "Teleport, Lightning_Spear, Rallying_Cry, Dash, Shadow_Step, Landslide",
    "Run Video": "https://www.youtube.com/watch?v=mIC8uA1dl0Y",
    "Run Comment": "Season 6 PTR",
    "Build Planner": "",
    Runewords: "War_Cry, Petrify",
  },
];
